[phases.setup]
nixPkgs = ["python311", "libgomp", "glib", "libsndfile"]

[phases.build]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.start]
cmds = ["sh start.sh"]

[variables]
PORT = "8000"
